version: "3.9"
services:
  app-grpc:
    image: test-target:grpc-v0.1.0
    ports:
    - "50051:50051"

  app-http:
    image: test-http:grpc-v0.1.0
    ports:
    - "3000:3000"

  app-media:
    image: test-media:grpc-v0.1.0
    ports:
    - "8000:8000"
    
  app-graphql:
    image: test-graphql:grpc-v0.1.0
    ports:
    - "4000:4000"
