---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ptaas.fullname" . }}-base-configmap
  namespace: '{{ .Release.Namespace }}'
  labels:
    {{- include "ptaas.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- toYaml .Values.base.configs | default "{}" | nindent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ptaas.fullname" . }}-gateway-configmap
  namespace: '{{ .Release.Namespace }}'
  labels:
    {{- include "ptaas.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- toYaml .Values.gateway.configs | default "{}" | nindent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ptaas.fullname" . }}-dashboard-configmap
  namespace: '{{ .Release.Namespace }}'
  labels:
    {{- include "ptaas.labels" . | nindent 4 }}
data:
  .env: |
    VITE_API_URL={{ .Values.dashboard.configs.gateway }}
    VITE_VERSION={{ .Values.dashboard.configs.version }}