---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ptaas.fullname" . }}-base
  labels:
    {{- include "ptaas.labels" . | nindent 4 }}
spec:
  {{- if not .Values.base.autoscaling.enabled }}
  replicas: {{ .Values.base.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "ptaas.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.base.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "ptaas.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.base.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "ptaas.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.base.podSecurityContext | nindent 8 }}
      volumes:
        - name: base-config
          configMap:
            name: {{ include "ptaas.fullname" . }}-base-configmap
      containers:
        - name: {{ .Chart.Name }}-base
          securityContext:
            {{- toYaml .Values.base.securityContext | nindent 12 }}
          image: "{{ .Values.base.image.repository }}:{{ .Values.base.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.base.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 9090
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
          resources:
            {{- toYaml .Values.base.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /app/scanner/config.yaml
              name: base-config
              subPath: config.yaml
      {{- with .Values.base.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.base.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.base.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ptaas.fullname" . }}-gateway
  labels:
    {{- include "ptaas.labels" . | nindent 4 }}
spec:
  {{- if not .Values.gateway.autoscaling.enabled }}
  replicas: {{ .Values.gateway.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "ptaas.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.gateway.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "ptaas.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.gateway.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "ptaas.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.gateway.podSecurityContext | nindent 8 }}
      volumes:
        - name: gateway-config
          configMap:
            name: {{ include "ptaas.fullname" . }}-gateway-configmap
      containers:
        - name: {{ .Chart.Name }}-gateway
          securityContext:
            {{- toYaml .Values.gateway.securityContext | nindent 12 }}
          image: "{{ .Values.gateway.image.repository }}:{{ .Values.gateway.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.gateway.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
          resources:
            {{- toYaml .Values.gateway.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /app/config.yaml
              name: gateway-config
              subPath: config.yaml
      {{- with .Values.gateway.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.gateway.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.gateway.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ptaas.fullname" . }}-ftp
  labels:
    {{- include "ptaas.labels" . | nindent 4 }}
spec:
  {{- if not .Values.ftp.autoscaling.enabled }}
  replicas: {{ .Values.ftp.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "ptaas.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.ftp.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "ptaas.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.ftp.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "ptaas.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.ftp.podSecurityContext | nindent 8 }}
      volumes:
        - name: data-dir
          emptyDir: { }
      containers:
        - name: {{ .Chart.Name }}-ftp
          securityContext:
            {{- toYaml .Values.ftp.securityContext | nindent 12 }}
          image: "{{ .Values.ftp.image.repository }}:{{ .Values.ftp.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.ftp.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 9091
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
          resources:
            {{- toYaml .Values.ftp.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /app/data/docs
              name: data-dir
          env:
            - name: HTTP_PORT
              value: {{ .Values.ftp.configs.port }}
            - name: ACCESS_KEY
              value: {{ .Values.ftp.configs.access }}
            - name: PRIVATE_KEY
              value: {{ .Values.ftp.configs.secret }}
            - name: MINIO_CLUSTER
              value: {{ .Values.ftp.configs.minio }}
      {{- with .Values.ftp.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ftp.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ftp.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ptaas.fullname" . }}-dashboard
  labels:
    {{- include "ptaas.labels" . | nindent 4 }}
spec:
  {{- if not .Values.dashboard.autoscaling.enabled }}
  replicas: {{ .Values.dashboard.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "ptaas.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.dashboard.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "ptaas.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.dashboard.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "ptaas.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.dashboard.podSecurityContext | nindent 8 }}
      volumes:
        - name: dashboard-config
          configMap:
            name: {{ include "ptaas.fullname" . }}-dashboard-configmap
      containers:
        - name: {{ .Chart.Name }}-dashboard
          securityContext:
            {{- toYaml .Values.dashboard.securityContext | nindent 12 }}
          image: "{{ .Values.dashboard.image.repository }}:{{ .Values.dashboard.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.dashboard.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.dashboard.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /usr/share/nginx/html/.env
              name: dashboard-config
              subPath: .env
      {{- with .Values.dashboard.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.dashboard.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.dashboard.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
