apiVersion: v1
kind: Service
metadata:
  name: {{ include "ptaas.fullname" . }}
  labels:
    {{- include "ptaas.labels" . | nindent 4 }}
spec:
  type: {{ .Values.base.service.type }}
  ports:
    - port: {{ .Values.base.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "ptaas.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ptaas.fullname" . }}
  labels:
    {{- include "ptaas.labels" . | nindent 4 }}
spec:
  type: {{ .Values.gateway.service.type }}
  ports:
    - port: {{ .Values.gateway.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "ptaas.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ptaas.fullname" . }}
  labels:
    {{- include "ptaas.labels" . | nindent 4 }}
spec:
  type: {{ .Values.ftp.service.type }}
  ports:
    - port: {{ .Values.ftp.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "ptaas.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ptaas.fullname" . }}
  labels:
    {{- include "ptaas.labels" . | nindent 4 }}
spec:
  type: {{ .Values.dashboard.service.type }}
  ports:
    - port: {{ .Values.dashboard.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "ptaas.selectorLabels" . | nindent 4 }}
