base:
  replicaCount: 1
  image:
    repository: amirhossein21/ptaas-tool
    pullPolicy: IfNotPresent
    tag: "base-v0.4.0"
  imagePullSecrets: [ ]
  nameOverride: ""
  fullnameOverride: ""
  podAnnotations: { }
  podSecurityContext: { }
  securityContext: { }
  service:
    type: ClusterIP
    port: 9090
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
  nodeSelector: { }
  tolerations: [ ]
  affinity: { }
  configs:
    core:
      port: 9090
      enable: true
      workers: 1
      secret: "secret"
    mysql:
      host: 'localhost'
      port: 3306
      user: root
      pass: ''
      database: 'apt'
      migrate: false
    migrate:
      root: 'admin'
      pass: '12345'
      enable: true
    ai:
      enable: true
      method: "svm"
      "limit": 10
      "factor": 7
    scanner:
      enable: true
      defaults:
        - "2fa"
      command: "python3 scanner.py"
      flags:
        - "host"
        - "endpoints"
        - "type"
        - "protocol"
    ftp:
      host: 'http://localhost:9091'
      secret: 'secret'
      access: 'access'

gateway:
  replicaCount: 1
  image:
    repository: amirhossein21/ptaas-tool
    pullPolicy: IfNotPresent
    tag: "gateway-v0.4.0"
  imagePullSecrets: [ ]
  nameOverride: ""
  fullnameOverride: ""
  podAnnotations: { }
  podSecurityContext: { }
  securityContext: { }
  service:
    type: ClusterIP
    port: 8080
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
  nodeSelector: { }
  tolerations: [ ]
  affinity: { }
  configs:
    http:
      port: 8080
      core: 'http://localhost:9090/api'
      core_secret: 'secret'
      dev_mode: true
    jwt:
      private_key: 'super'
      expire_time: 180 # minute
    mysql:
      host: 'localhost'
      port: 3306
      user: root
      pass: ''
      database: 'apt'
      migrate: false
    ftp:
      host: 'http://localhost:9091'
      secret: 'secret'
      access: 'access'

ftp:
  replicaCount: 1
  image:
    repository: amirhossein21/ptaas-tool
    pullPolicy: IfNotPresent
    tag: "ftp-v0.4.0"
  imagePullSecrets: [ ]
  nameOverride: ""
  fullnameOverride: ""
  podAnnotations: { }
  podSecurityContext: { }
  securityContext: { }
  service:
    type: ClusterIP
    port: 9091
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
  nodeSelector: { }
  tolerations: [ ]
  affinity: { }
  configs:
    port: 9091
    access: "access"
    secret: "secret"
    minio: "minio.cluster.default.svc.local"

dashboard:
  replicaCount: 1
  image:
    repository: amirhossein21/ptaas-tool
    pullPolicy: IfNotPresent
    tag: "dash-v0.4.0"
  imagePullSecrets: [ ]
  nameOverride: ""
  fullnameOverride: ""
  podAnnotations: { }
  podSecurityContext: { }
  securityContext: { }
  service:
    type: ClusterIP
    port: 80
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
  nodeSelector: { }
  tolerations: [ ]
  affinity: { }
  configs:
    gateway: "http://localhost:8080"
    version: "v0.5.0"
