base:
  replicaCount: 1
  image:
    repository: amirhossein21/ptaas-tool
    pullPolicy: IfNotPresent
    tag: "base-v0.4.0"
  imagePullSecrets: [ ]
  nameOverride: ""
  fullnameOverride: ""
  podAnnotations: { }
  podSecurityContext: { }
  securityContext: { }
  service:
    type: ClusterIP
    port: 9090
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
  nodeSelector: { }
  tolerations: [ ]
  affinity: { }
  configs: { }

gateway:
  replicaCount: 1
  image:
    repository: amirhossein21/ptaas-tool
    pullPolicy: IfNotPresent
    tag: "gateway-v0.4.0"
  imagePullSecrets: [ ]
  nameOverride: ""
  fullnameOverride: ""
  podAnnotations: { }
  podSecurityContext: { }
  securityContext: { }
  service:
    type: ClusterIP
    port: 8080
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
  nodeSelector: { }
  tolerations: [ ]
  affinity: { }
  configs: { }

ftp:
  replicaCount: 1
  image:
    repository: amirhossein21/ptaas-tool
    pullPolicy: IfNotPresent
    tag: "ftp-v0.4.0"
  imagePullSecrets: [ ]
  nameOverride: ""
  fullnameOverride: ""
  podAnnotations: { }
  podSecurityContext: { }
  securityContext: { }
  service:
    type: ClusterIP
    port: 9091
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
  nodeSelector: { }
  tolerations: [ ]
  affinity: { }
  configs:
    port: 9091
    access: "access"
    secret: "secret"
    minio: "cluster"

dashboard:
  replicaCount: 1
  image:
    repository: amirhossein21/ptaas-tool
    pullPolicy: IfNotPresent
    tag: "dash-v0.4.0"
  imagePullSecrets: [ ]
  nameOverride: ""
  fullnameOverride: ""
  podAnnotations: { }
  podSecurityContext: { }
  securityContext: { }
  service:
    type: ClusterIP
    port: 80
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
  nodeSelector: { }
  tolerations: [ ]
  affinity: { }
  configs:
    gateway: "http://localhost:8080"
    version: "v0.4.0"
