core:
  port: 9090
  enable: true
  workers: 1
  secret: "#wercV89Qwerc09"
mysql:
  host: "mysql-container"
  port: 3306
  user: root
  pass: "mauFJcuf5dhRMQrjj"
  database: "ptaas"
  migrate: true
ai:
  enable: false
  method: "random"
  "limit": 10
  "factor": 7
scanner:
  enable: false
  defaults:
    - "2fa"
  command: "python3 scanner.py"
  flags:
    - "host"
    - "endpoints"
    - "type"
    - "protocol"
migrate:
  root: "admin"
  pass: "12345"
  enable: false
ftp:
  host: "http://ftp-server:9091"
  secret: "8bVc13329vn23"
  access: "nnvXiu%2234nvoo3n1i98n3v"
